### ISSUE TITLE
SUMMIT timeout with 954 GPUs 

### ISSUE THREAD

**Issue by agemagician** [IBM/powerai#141]
Hi,

I am running a deep learning model on SUMMIT using Horovod and IBM-WML v1.6.1, the script runs without any issue when I use 10 nodes. However, when I large scale it to 954 nodes, it gives timeout error as follows:
    
```
      Please see /tmp/DDLRUN/DDLRUN.XwpRxX61zQZ1/ddlrun.log for detailed log.
    
      [WARN DDL-2-28] The SKIPCHECKS flag is set. This removes the ability for
      'ddlrun' to detect remote hardware configurations and can cause errors in
      non-homogenous cluster environments - i.e., machines with varying core or
      GPU counts.
    
      Please see /tmp/DDLRUN/DDLRUN.XwpRxX61zQZ1/ddlrun.log for detailed log.
    
      --------------------------------------------------------------------------
    
      The user-provided time limit for job execution has been reached:
    
      Timeout: 180 seconds
    
      The job will now be aborted. Please check your code and/or
    
      adjust/remove the job execution time limit (as specified by --timeout
    
      command line option or MPIEXEC_TIMEOUT environment variable).
```

I tried to pass the timeout variable but it doesn't accept it:
`ddlrun  --verbose -mpiarg "-timeout 600" ......`

I also tried to export "MPIEXEC_TIMEOUT", but it has no effect:
`export MPIEXEC_TIMEOUT=600`

Could you please provide the correct way to increase the timeout value with ibm-wml v.1.6.1 ?

**Comment by nvcastet** [comment]
@agemagician Please try `ddlrun -v --debug_timeout 600 ...`, let us know if it works.
Also, Bryant mentioned they fixed a similar issued on Summit, so make sure you are using the latest conda environment from the WMLCE module.

**Comment by bethune-bryant** [comment]
@agemagician 
This may be a configuration issue that we fixed Saturday morning.

When did you run the job?
Are you running out of a clone environment or directly from the module?
Can you provide the rest of the output?

**Comment by agemagician** [comment]
@nvcastet :
I made several tests with 14 nodes, and I was able finally to override the MPIEXEC_TIMEOUT by using the following command:
`ddlrun --nodes 14 --racks 1 --aisles 1 --verbose -x MPIEXEC_TIMEOUT=604800 -x NCCL_DEBUG=INFO python train.py ..........`

It is just strange that the default  MPIEXEC_TIMEOUT is set to 180.

I will retry again with 9xx nodes, and I will give my feedback again.

@bethune-bryant :

When did you run the job?
The job started on "Nov 2 22:13"

Are you running out of a clone environment or directly from the module?
I load ibm-wml-ce module and then I activate my own "ibm-wml-ce" clone, because I needed to install more extra libiraries.

Can you provide the rest of the output?
This is the whole output:
```
[WARN DDL-2-39] Running on more than 10 nodes. Skipping checks for performance.
Please see /tmp/DDLRUN/DDLRUN.ynkMioC4FaUh/ddlrun.log for detailed log.
[WARN DDL-2-28] The SKIPCHECKS flag is set. This removes the ability for 'ddlrun' to detect remote hardware configurations and can cause errors in non-homogenous cluster environments - i.e., machines with varying core or GPU counts.
Please see /tmp/DDLRUN/DDLRUN.ynkMioC4FaUh/ddlrun.log for detailed log.
--------------------------------------------------------------------------
The user-provided time limit for job execution has been reached:

  Timeout: 180 seconds

The job will now be aborted.  Please check your code and/or
adjust/remove the job execution time limit (as specified by --timeout
command line option or MPIEXEC_TIMEOUT environment variable).
--------------------------------------------------------------------------

[ERROR DDL-2-10] An error was encountered trying to generate the rankfile.
Please see /tmp/DDLRUN/DDLRUN.ynkMioC4FaUh/ddlrun.log for detailed log.
```

**Comment by bethune-bryant** [comment]
@agemagician 
This is the problem that we fixed. You will need to update the DDL package in your environment to build `py36_1213_SUMMIT.g6248048` or `py27_1213_SUMMIT.g6248048`.

**Comment by agemagician** [comment]
@bethune-bryant 
Today, I just made a new clone and It matches your recommended build:
`ddl                       1.4.0.1         py36_1213_SUMMIT.g6248048    file:///sw/sources/ibm-wml-ce/conda-channel`

I hope it will work this time.
I just executed a new run with 936 nodes, and I will report back once it started.

**Comment by bethune-bryant** [comment]
@agemagician 
Greate! That should work.
For some better performance you may want to go ahead and add:
`--mode bn`

Also, specifying a topology tends to help performance on very large node counts. Something like:
` --nodes 18 --racks 4 --aisles 13`

**Comment by agemagician** [comment]
@bethune-bryant 

Thanks a lot for the tip. I was already using the advanced reservation mode, but I didn't change the default mode parameter.
I just add it to my script.

Here is my current bash file :

```
#!/bin/bash
# Begin LSF Directives
#BSUB -P bif120
#BSUB -W 24:00
#BSUB -csm y
#BSUB -n 39313
#BSUB -R 1*{select[((LN)&&(type==any))]order[r15s:pg]span[hosts=1]cu[type=rack:pref=config]}+39312*{select[((CN)&&(type==any))]order[r15s:pg]span[ptile=42]cu[type=rack:maxcus=52]}
#BSUB -q batch
#BSUB -alloc_flags "smt4 NVME"
#BSUB -J TXL_LS
#BSUB -o /ccs/proj/bif120/deepforce/lsf_job/TXL_936.o%J
#BSUB -e /ccs/proj/bif120/deepforce/lsf_job/TXL_936.e%J
#BSUB -N

......

module load ibm-wml-ce
conda activate ibm_wml_ce-1.6.1


ddlrun --nodes 18 --racks 4 --aisles 13 --verbose --mode bn -x MPIEXEC_TIMEOUT=604800 -x NCCL_DEBUG=INFO python train.py .......

```

Any more suggestions/tips for better performance ?

**Comment by bethune-bryant** [comment]
@agemagician 

That should get you good performance.

Let me know if this doesn't work, or if you run into any more problems!

**Comment by agemagician** [comment]
@bethune-bryant @nvcastet 

Thanks a lot, the job finally executed successfully and the problem is solved.

I will close the issue, and thanks again for your help.
