### ISSUE TITLE
Pytorch 1.4+ build with CUDA 10.1 on power8/p100 cluster - crashes the node

### ISSUE THREAD

**Issue by denfromufa** [IBM/powerai#185]
I'm trying to build pytorch from source in PowerAI 1.6.2 WML environment with custom MPI/NCCL options. 

When I switched from CUDA/10.1 module (distro package) to cudatoolkit-dev package from powerai conda, this killed the development node with 4 GPUs 😮 See the attached traceback:

[node.killed.pytorch.compile.source.txt](https://github.com/IBM/powerai/files/4002912/node.killed.pytorch.compile.source.txt)

cc @bethune-bryant @smatzek @nvcastet @wdirons @hartb 

More details in this issue:

https://github.com/pytorch/pytorch/issues/31438

**Comment by hartb** [comment]
Commented on the issue in the pytorch repo (given a crash, my suspicion would be something more like a kernel or driver issue).

**Comment by denfromufa** [comment]
the crash is not reproducible, most likely caused by not updated cudatoolkit-dev or out of memory during compilation.
