### ISSUE TITLE
support of pytorch 1.6.0 and torchvision 0.7.0

### ISSUE THREAD

**Issue by brando90** [IBM/powerai#271]
Can we have the latest pytorch versions please?

**Comment by vc1492a** [comment]
Please!

**Comment by jayfurmanek** [comment]
Development has moved to an open project called Open Cognitive Environment (https://github.com/open-ce/open-ce).
Please join us! The first release of Open-CE does indeed includes PyTorch 1.6 and torchvision 0.7.0.

PyTorch 1.7.0 has tagged upstream, and we'll include that in the next Open-CE release. We are waiting for TF2.4 to tag and will integrate. Working PRs are up for these updates already.

Note that Open-CE is a set of recipes, tools and build scripts. So you have a few options:
 - build everything locally - this can be done with a single command - check the docs
        - https://github.com/open-ce/open-ce/tree/open-ce-v1.0.1/doc
        - https://github.com/open-ce/open-ce/blob/open-ce-v1.0.1/README.md
 - build everything on Tekton/Openshift (coming soon)
 - Use prebuilt packages from other community members include Oregon State University (https://osuosl.org/)
        - https://ftp.osuosl.org/pub/open-ce/1.0.0/
