### ISSUE TITLE
Where is tensorflow lib?

### ISSUE THREAD

**Issue by dnguyenv** [IBM/powerai#3]
Hi,
I'm trying this image on POWER https://hub.docker.com/r/ibmcom/powerai/ 
In Dockerfile:
`FROM ibmcom/powerai:1.5.3-all-ubuntu16.04-py3` 

Once activated the `tensorflow` packages while launching a container, where is tensorflow lib located to which I can do `import tensorflow as tf` in Python code within the container?

**Comment by hartb** [comment]
Hello!

A ways down in the desription page for that image (https://hub.docker.com/r/ibmcom/powerai/) there's an **Installed Packages** section that lists the versions of the PowerAI packages in the image. The package versions often change from one PowerAI version to the next, so the table describes both current and older image versions.

For PowerAI 1.5.3 the included TensorFlow version is 1.10.0.

Most of the PowerAI packages unpack into `/opt/DL/...` (so `/opt/DL/tensorflow/` for TF in particular). 
But you _mostly_ shouldn't need to worry about that when using PowerAI's TF.

You should be able to just:

```
$ source /opt/DL/tensorflow/bin/tensorflow-active   # will set up PATH, PYTHONPATH, etc.

$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:38:54) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
```

**Comment by dllehr81** [comment]
@dnguyenv ..are we okay closing out this, did @hartb successfully answer your question?  Please let us know if there's anything else we can do!

**Comment by jayfurmanek** [comment]
Note that in PowerAI 1.6.0, we've moved all of the packages to conda, so these activation scripts are no longer necessary. It is recommended to create and activate a new conda env, however, but that is not required.
