### ISSUE TITLE
Support for Pytorch 1.0?

### ISSUE THREAD

**Issue by mark-hoffmann** [IBM/powerai#7]
I saw that the only version of Pytorch currently supported in the docker images are 0.4.0 and 0.4.1. Is there any way a 1.0 build can be supported?

I've tried installing from source and it is a massive headache using powerpc as opposed to another linux machine.

**Comment by hartb** [comment]
Hello!

We'll refresh PyTorch to a 1.0-based version in the next release of PowerAI.  PyTorch upstream 1.0 is still in RC / development preview mode, and we expect that will likely continue at least until early December. (See, for example: https://towardsdatascience.com/a-first-look-at-pytorch-1-0-8d3cce20b3ee .)

The next release of PowerAI should come out before then, though, so it will include a build of PyTorch 1.0 RC (including Caffe2). The PowerAI Docker Hub image will be refreshed to include the same. (Note it will transition to an Ubuntu 18.04 & CUDA 10 base, from the 16.04 / CUDA 9.2 we include today.)

So the upcoming PowerAI release should contain what you need if you can wait a bit.

Longer term, we'll continue to refresh PowerAI periodically from current upstream. We also hope to work out a way to make frequent Power builds available to customers even between PowerAI releases. That's still a work in progress, though.

If you can't wait for the next PowerAI release, feel free to share any troubles you're hitting when building on Power. We'll be happy to offer any advice we can.

Thank you!
brian

**Comment by dllehr81** [comment]
@mark-hoffmann  ..are we okay closing out this, did @hartb successfully answer your question?  Please let us know if there's anything else we can do!

**Comment by mark-hoffmann** [comment]
Yes thank you! I ended up finding another solution for the time being, but will be on the lookout once the new docker images are available!

**Comment by jayfurmanek** [comment]
Note that the latest PowerAI (1.6.0) is now up, does indeed include the latest PyTorch (1.0.1) and has many other new things as well!
