### ISSUE TITLE
[recipe request] imageai

### ISSUE THREAD

**Issue by alex-coda-13** [IBM/powerai#81]
- Name of package: imageai
- License of package: MIT
- URL of package source code: 

https://github.com/OlafenwaMoses/ImageAI

- List of package dependencies:  (everything is already installed) 

Python 3.5.1 (and later versions) (Support for Python 2.7 coming soon)
Tensorflow 1.4.0 (and later versions)
OpenCV
Keras 2.x
Requirement already satisfied: matplotlib (3.0.3)
Requirement already satisfied: pillow (5.3.0)
Requirement already satisfied: scipy (1.1.0)
Requirement already satisfied: h5py (2.8.0)
Requirement already satisfied: numpy (1.14.5)
Requirement already satisfied: cycler>=0.10 (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1  (1.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (2.3.1)
Requirement already satisfied: python-dateutil>=2.1 (2.8.0)
Requirement already satisfied: six  (1.12.0)
Requirement already satisfied: setuptools  (40.8.0)

- Short description of package:

ImageAI is an easy to use Computer Vision Python library that empowers developers to easily integrate state-of-the-art Artificial Intelligence features into their new and existing applications and systems. It implements several relevant algorithms such as DenseNet for classification. It is based on TensorFlow. It also implements object detection models. 

- Use cases: 

ImageAI provides API to train new image recognition models on new image datasets for custom use cases. It also provides implementations to integrate and deploy the custom image recognition models

In our case, we would use the two features (classification and object detection) for car claim analysis. Object detection would be used on car damages.

NB: This project is leaded in the frame of tests on powerAI cluster, leaded by Guilhaume Leroy-Meline in IBM France.

**Comment by npanpaliya** [comment]
https://anaconda.org/powerai/imageai

**Comment by npanpaliya** [comment]
PR - https://github.com/IBM/powerai/pull/82/

**Comment by jayfurmanek** [comment]
Available now! Thanks!
